source 'https://rubygems.org'

gem 'coffee-script' # coffeescript
gem 'dotenv'        # config via environment variables
gem 'graphlient'    # graphql client
gem 'kramdown'      # markdown templates
gem 'pry'           # debugger
gem 'rerun'         # auto-reload app on code changes
gem 'rest-client'   # needed by solargraph
gem 'sinatra'       # app server
gem 'sinatra-flash' # error and success messages
gem 'slim'          # slim templates
gem 'solargraph'    # ruby language server for development

github 'sinatra/sinatra' do
  gem 'sinatra-contrib' # sinatra extensions
end
