source "https://rubygems.org"

gem 'pry'           # debugger
gem 'graphlient'    # graphql client
gem 'kramdown'      # markdown templates
gem 'slim'          # slim templates
gem 'dotenv'        # config via environment variables
gem 'sinatra'       # app server
gem 'sinatra-flash' # error and success messages
gem 'rerun'         # auto-reload app on code changes
gem 'solargraph'    # ruby language server for development
gem 'rest-client'   # needed by solargraph

github 'sinatra/sinatra' do 
  gem 'sinatra-contrib' # sinatra extensions
end

