#!/usr/bin/env bash

export BUNDLE_GEMFILE=~/src/bugmark/test_bench/exercise/Gemfile

echo "-----"
echo "STARTING WEBAPP"
echo "GEMFILE IS $BUNDLE_GEMFILE"

[ -d ./webapp ] && cd webapp

rerun 'bundle exec rackup -p 4567 -o 0.0.0.0'
