---
exchange_url: http://hana:3000
admin_username: admin@bugmark.net
admin_password: bugmark
leader_name: Andy Leak 
leader_email: andy@r210.com
participants:
  - andy@r210.com
  - test1@bugmark.net
  - test2@bugmark.net
  - test3@bugmark.net
  - test4@bugmark.net
tracker_type: github
repo_list:
  - Bugmark-Simulator/bugmark_simulation
  - bugmark/test_bench
  - bugmark/website
  - bugmark/exchange
  - bugmark/outreachy
  - bugmark/awesome-bugmark 
  - bugmark/iora
  - bugmark/paypro
  - bugmark/bmx_cl_ruby
  - bugmark/bmx_bots
  - casmacc/nginx_proxy
  - casmacc/website
  - casmacc/lead_capture
  - casmacc/html_helloworld
  - casmacc/slackin
  - casmacc/phoenix_helloworld
  - casmacc/sinatra_helloworld
  - casmacc/mail_proxy

